version: '3'

services:
  validator-service:
    build:
      context: ./validator_service
    ports:
      - "3001:3000"
    depends_on:
      - database

  add-service:
    build:
      context: ./add_service
    ports:
      - "3002:3000"
    depends_on:
      - database

  database:
    image: mongo
    ports:
      - "27017:27017"

  load-balancer:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
